language: ruby
rvm:
  - 2.2.3
branches:
  only:
    - master
deploy:
  provider: heroku
  app: saml-inspect
  strategy: git
  on:
    branch: master
    repo: tlatsas/saml-inspect
  api_key:
    secure: U3rRAn+TGKQMeUu8Vxz7ZfCFlm5lmuzw700dqgf3FwZ9ZVdEIviC/S1gt20Ipq06Su1dBpjd1TtjcIufHBlZdw200ZS4wo1rLfyoP30OFgepTdlr3RFFZGfYED9jTzLV4MiebEHkhP1FybnOQgqgbZ3iaTBirrjcoKm5DjSw4fs=
